apiVersion: batch/v1
kind: Job
metadata:
  name: fail2
spec:
  template:
    spec:
      containers:
      - name: fail2
        image: alpine
        command: ["exit", "1"]
      nodeName: agent2
      restartPolicy: Never
  backoffLimit: 4
